export const validationRules = {
  base: {
    required: true,
    minLength: 3,
    maxLength: 100,
  },
  nome: {
    required: true,
    functionName: 'validaNome',
  },
  mensagem: {
    required: true,
    functionName: 'validaMensagem',
  },
  documento: {
    minLength: 14,
    maxLength: 14,
    functionName: 'validaDoc',
  },
  documentoEntrar: {
    minLength: 14,
    maxLength: 14,
    functionName: 'validaDoc',
  },
  telefone: {
    required: false,
    minLength: 14,
    maxLength: 15,
    functionName: 'validaTelefone',
  },
  nascimento: {
    minLength: 10,
    maxLength: 10,
    regex: '^\\d{2}\\/\\d{2}\\/\\d{4}$',
    functionName: 'validaDataNascimento',
  },
  email: {
    minLength: 5,
    maxLength: 50,
    regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$',
  },
  confirmarEmail: {
    minLength: 5,
    maxLength: 50,
    equalsTo: 'email',
    regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$',
  },
  senha: {
    minLength: 8,
    maxLength: 50,
    functionName: 'validaSenha',
  },
  confirmarSenha: {
    minLength: 8,
    maxLength: 50,
    equalsTo: 'senha',
    functionName: 'validaSenha',
  },
  genero: {
    minLength: 1,
    maxLength: 1,
    options: ['M', 'F', 'O'],
  },
  cep: {
    minLength: 9,
    maxLength: 9,
    regex: '^\\d{5}-\\d{3}$',
  },
  complemento: {
      minLength: 1,
  
    required: false,
  },
  uf: {
    minLength: 2,
    maxLength: 2,
    options: [
      'AC',
      'AL',
      'AP',
      'AM',
      'BA',
      'CE',
      'DF',
      'ES',
      'GO',
      'MA',
      'MT',
      'MS',
      'MG',
      'PA',
      'PB',
      'PR',
      'PE',
      'PI',
      'RJ',
      'RN',
      'RS',
      'RO',
      'RR',
      'SC',
      'SP',
      'SE',
      'TO',
    ],
  },
  numero: {
    required: true,
    minLength: 1,
    maxLength: 10,
  },
  regulamento: {
    minLength: null,
    maxLength: null,
    options: [true],
  },
  politica: {
    minLength: null,
    maxLength: null,
    options: [true],
  },
  mailing: {
    minLength: null,
    maxLength: null,
    options: [true, false],
  },
  chaveAcesso: {
    minLength: 54,
    maxLength: 54,
    regex:
      '^\\d{4} \\d{4} \\d{4} \\d{4} \\d{4} \\d{4} \\d{4} \\d{4} \\d{4} \\d{4} \\d{4}$',
  },
  pincode: {
    minLength: 17,
    maxLength: 17,
    regex: '^[A-Za-z]{1,17}$',
  },
  numeroPedido: {
    minLength: 15,
    maxLength: 15,
    regex: '^[0-9]{1,15}$',
  },
};
